
pipelines:
  branches:
    master:
      - step:
          image: python:3.7.2
          name: Master siempre funciona
          script:
            - pip install -r requirements.txt
            - python -m unittest discover tests/
          artifacts:
            - dist/**
      - step:
          name: Publicación de versión en PyPI
          trigger: manual
          script:
            - pipe: atlassian/pypi-publish:0.2.4
              variables:
                PYPI_USERNAME: $PYPI_USERNAME
                PYPI_PASSWORD: $PYPI_PASSWORD
                REPOSITORY: 'https://test.pypi.org/legacy/'
