
pipelines:
  branches:
    master:
      - step:
          image: python:3.5.2
          name: Master siempre funciona
          script:
            - pip install -r requirements.txt
            - python -m unittest discover tests/
            - python3 setup.py clean --all sdist bdist_wheel
          artifacts:
            - dist/**
      - step:
          name: Publicaci贸n de versi贸n en PyPI Test
          trigger: manual
          deployment: test
          script:
            - pipe: atlassian/pypi-publish:0.2.7
              variables:
                PYPI_USERNAME: $PYPI_USERNAME
                PYPI_PASSWORD: $PYPI_PASSWORD
                REPOSITORY: $PYPI_REPO_URL
      - step:
          name: Publicaci贸n de versi贸n en PyPI
          trigger: manual
          deployment: production
          script:
            - pipe: atlassian/pypi-publish:0.2.7
              variables:
                PYPI_USERNAME: $PYPI_USERNAME
                PYPI_PASSWORD: $PYPI_PASSWORD
                REPOSITORY: $PYPI_REPO_URL

  pull-requests:
    '**':
      - step:
          image: python:3.5.2
          caches:
            - pip
          name: PR funciona
          script:
            - pip install -r requirements.txt
            - python -m unittest discover tests/
          artifacts:
            - dist/**
